name: Test – Trigger-test

on:
  issues:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo label
        run: |
          echo "Label namn: ${{ github.event.label.name }}"
          echo "Issue nummer: ${{ github.event.issue.number }}"
          echo "Issue titel: ${{ github.event.issue.title }}"
